<?xml version="1.0" encoding="utf-8"?><Database Name="NorthVilleDatabase by RM AND JS" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=HERZSPRUNG\SQLEXPRESS;Initial Catalog=&quot;NorthVilleDatabase by RM AND JS&quot;;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="WpfApp3.Properties.Settings" SettingsPropertyName="NorthVilleDatabase_by_RM_AND_JSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users_table" Member="Users_tables">
    <Type Name="Users_table">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_AvailableCopies" Member="vw_AvailableCopies">
    <Type Name="vw_AvailableCopy">
      <Column Name="I_ISBNID" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="I_BookName" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="AvailableCopies" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Book" Member="Books">
    <Type Name="Book">
      <Column Name="B_BookID" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="G_GenreID" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="I_ISBNID" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Book_BorrowTransaction" Member="BorrowTransactions" ThisKey="B_BookID" OtherKey="B_BookID" Type="BorrowTransaction" />
      <Association Name="ISBN_Book" Member="ISBN" ThisKey="I_ISBNID" OtherKey="I_ISBNID" Type="ISBN" IsForeignKey="true" />
      <Association Name="Genre_Book" Member="Genre" ThisKey="G_GenreID" OtherKey="G_GenreID" Type="Genre" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BorrowTransaction" Member="BorrowTransactions">
    <Type Name="BorrowTransaction">
      <Column Name="T_TransactionID" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="N_StudentID" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="T_BorrowDate" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="B_BookID" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="T_ReturnDate" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="T_TransactionNote" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="BorrowTransaction_LibraryVisit" Member="LibraryVisits" ThisKey="T_TransactionID" OtherKey="T_TransactionID" Type="LibraryVisit" />
      <Association Name="Book_BorrowTransaction" Member="Book" ThisKey="B_BookID" OtherKey="B_BookID" Type="Book" IsForeignKey="true" />
      <Association Name="NorthVilleStudent_BorrowTransaction" Member="NorthVilleStudent" ThisKey="N_StudentID" OtherKey="N_StudentID" Type="NorthVilleStudent" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NorthVilleStudent" Member="NorthVilleStudents">
    <Type Name="NorthVilleStudent">
      <Column Name="N_StudentID" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="N_FirstName" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="N_LastName" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="N_Email" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="N_PhoneNumber" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="C_CourseID" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="NorthVilleStudent_BorrowTransaction" Member="BorrowTransactions" ThisKey="N_StudentID" OtherKey="N_StudentID" Type="BorrowTransaction" />
      <Association Name="NorthVilleStudent_LibraryVisit" Member="LibraryVisits" ThisKey="N_StudentID" OtherKey="N_StudentID" Type="LibraryVisit" />
      <Association Name="Course_NorthVilleStudent" Member="Course" ThisKey="C_CourseID" OtherKey="C_CourseID" Type="Course" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LibraryVisit" Member="LibraryVisits">
    <Type Name="LibraryVisit">
      <Column Name="L_LibraryVisitID" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="N_StudentID" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="T_TransactionID" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="L_LibraryVisitDate" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="L_LibraryInTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="L_LibraryOutTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Association Name="NorthVilleStudent_LibraryVisit" Member="NorthVilleStudent" ThisKey="N_StudentID" OtherKey="N_StudentID" Type="NorthVilleStudent" IsForeignKey="true" />
      <Association Name="BorrowTransaction_LibraryVisit" Member="BorrowTransaction" ThisKey="T_TransactionID" OtherKey="T_TransactionID" Type="BorrowTransaction" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ISBN" Member="ISBNs">
    <Type Name="ISBN">
      <Column Name="I_ISBNID" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="I_BookName" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="I_BookAuthor" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="I_PublicationYear" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="ISBN_Book" Member="Books" ThisKey="I_ISBNID" OtherKey="I_ISBNID" Type="Book" />
    </Type>
  </Table>
  <Table Name="dbo.Genre" Member="Genres">
    <Type Name="Genre">
      <Column Name="G_GenreID" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="G_GenreDescription" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Genre_Book" Member="Books" ThisKey="G_GenreID" OtherKey="G_GenreID" Type="Book" />
    </Type>
  </Table>
  <Table Name="dbo.vw_DailyFineCollection" Member="vw_DailyFineCollections">
    <Type Name="vw_DailyFineCollection">
      <Column Name="PaymentDate" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TotalCollected" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_LibraryVisitReport" Member="vw_LibraryVisitReports">
    <Type Name="vw_LibraryVisitReport">
      <Column Name="N_StudentID" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TotalVisits" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_OverdueBooksWithPayment" Member="vw_OverdueBooksWithPayments">
    <Type Name="vw_OverdueBooksWithPayment">
      <Column Name="N_StudentID" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="StudentName" Type="System.String" DbType="VarChar(511) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="BorrowDate" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ReturnDate" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DaysOverdue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FineAmount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaymentStatus" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_StudentBorrowHistory" Member="vw_StudentBorrowHistories">
    <Type Name="vw_StudentBorrowHistory">
      <Column Name="N_StudentID" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="StudentName" Type="System.String" DbType="VarChar(511) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="BorrowDate" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ReturnDate" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Course" Member="Courses">
    <Type Name="Course">
      <Column Name="C_CourseID" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="C_CourseName" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Course_NorthVilleStudent" Member="NorthVilleStudents" ThisKey="C_CourseID" OtherKey="C_CourseID" Type="NorthVilleStudent" />
    </Type>
  </Table>
  <Function Name="dbo.sp_BorrowBook" Method="sp_BorrowBook">
    <Parameter Name="StudentID" Parameter="studentID" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="BookID" Parameter="bookID" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="BorrowDate" Parameter="borrowDate" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_GenerateLibraryReport" Method="sp_GenerateLibraryReport">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ReturnBook" Method="sp_ReturnBook">
    <Parameter Name="TransactionID" Parameter="transactionID" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="ReturnDate" Parameter="returnDate" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.udf_GetTotalBooksBorrowed" Method="udf_GetTotalBooksBorrowed" IsComposable="true">
    <Parameter Name="StudentID" Parameter="studentID" Type="System.String" DbType="VarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.udf_GetTotalFine" Method="udf_GetTotalFine" IsComposable="true">
    <Parameter Name="StudentID" Parameter="studentID" Type="System.String" DbType="VarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
</Database>